### ISSUE TITLE
"mult" was not declared

### ISSUE THREAD

**Issue by aviclu** [libsusa/susa#1]
In "channel.h", line 134, there is a use of the function "mult" but it was not declared or implemented.

**Comment by kamarya** [comment]
Thank you for reporting the issue. The function "mult" has been renamed as "matmul". This is to follow the same naming convention used in TensorFlow, Numpy and Fortran.

**Comment by acrola** [comment]
Hi, Thanks. Can I receive your e-mail, please?

**Comment by acrola** [comment]
Dear Behrooz Kamary Aliabadi,

I wrote a cpp script using your libraries for bcjr isi channel equalization.
Unfortunately, my script doesn't work and outputs "nan"s instead of the
decoded word.

I wanted to ask you if you can help me debug this. Probably it is a bug in
my code, but it could be also in Susa's bcjr_decode code.

Many thanks,
Avi

**Comment by kamarya** [comment]
you find it by just running `git log` in the cloned repo on your local machine
